apiVersion: apps/v1
kind: Deployment
metadata:
  name: lubo-sampleapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lubo-sampleapp
  template:
    metadata:
      labels:
        app: lubo-sampleapp
    spec:
      initContainers:
        - name: lubo-sampleapp-migrate
          image: aboobus/sampleapp:main
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: lubo-sampleapp-postgres-secret
          args:
            - python
            - manage.py
            - migrate
      containers:
        - name: zlubo-sampleapp
          image: aboobus/sampleapp:main
          ports:
            - containerPort: 8000
          args: 
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8000
          envFrom:
            - secretRef:
                name: lubo-sampleapp-postgres-secret