apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lubo-sampleapp-certificate
spec:
  dnsNames:
  - 'lubo.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: lubo-sampleapp-cert